# Don't change this.
version: 1

# Available permissions (Self-exlpanatory):
# - easyheal.heal.self
# - easyheal.heal.others
# - easyheal.feed.self
# - easyheal.heal.others
# - easyheal.cooldown.bypass

# If set to false, no permission will be needed and the command will be accessible to everyone.

need_permission_to_heal_self: true
need_permission_to_heal_others: true
need_permission_to_feed_self: true
need_permission_to_feed_others: true

# 1 = 1 half heart (20 = full-life)
heal_amount: 20
feed_amount: 20

# If true, the player gets his saturation to be set to max when being fed.
give_saturation: true
saturation_amount: 20

# Cooldowns for players who don't have the easyheal.cooldown.bypass permission
feed:
  cooldown: true
  cooldown_value: 30

heal:
  cooldown: true
  cooldown_value: 30


# Placeholders:
# - %playerName% Player's minecraft username
messages:
  no_permission: "§cYou cannot use this command."
  heal_received: "§aYou have been healed."
  heal_other_success: "§eYou healed %playerName%"
