name: EasyHeal
main: com.edouardcourty.easyheal.EasyHeal
version: 1.0.0
author: "Edouard Courty"

commands:
  heal:
    description: Heals you or the selected player.
  feed:
    description: Feeds you or the selected player.
